// <auto-generated />
using System;
using BnSystem_Test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BnSystem_Test.Migrations
{
    [DbContext(typeof(StoreDb))]
    [Migration("20191119082549_add propety of models")]
    partial class addpropetyofmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BnSystem_Test.Models.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IBAN")
                        .HasMaxLength(20);

                    b.Property<string>("active_status")
                        .HasMaxLength(10);

                    b.Property<decimal?>("balance");

                    b.Property<DateTime?>("create_date");

                    b.Property<string>("create_user")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("update_date");

                    b.Property<string>("update_user")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BnSystem_Test.Models.AccTransfers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Accounts_Id");

                    b.Property<decimal>("Amount")
                        .HasMaxLength(50);

                    b.Property<string>("action_type")
                        .HasMaxLength(10);

                    b.Property<string>("active_status")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("create_date");

                    b.Property<string>("create_user")
                        .HasMaxLength(50);

                    b.Property<string>("is_calculated")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("update_date");

                    b.Property<string>("update_user")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Accounts_Id");

                    b.ToTable("AccTransfers");
                });

            modelBuilder.Entity("BnSystem_Test.Models.AccTransfers", b =>
                {
                    b.HasOne("BnSystem_Test.Models.Accounts", "Accounts")
                        .WithMany("AccTransfers")
                        .HasForeignKey("Accounts_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
